# Config file for automatic testing at travis-ci.org

branches:
 only:
  - master

language: python

matrix:
  include:
    - os: linux
      python: "3.4"

    - os: linux
      python: "3.3.5"

    - os: linux
      python: "2.7"

    - os: osx
      language: generic
      env:
        - PYTHONVERSION=3.4.5

    - os: osx
      language: generic
      env:
        - PYTHONVERSION=3.3.6

    - os: osx
      language: generic
      env:
        - PYTHONVERSION=2.7.12

cache:
  directories:
    - $HOME/.pyenv/versions/3.4.5
    - $HOME/.pyenv/versions/3.3.6
    - $HOME/.pyenv/versions/2.7.12

addons:
  apt:
    packages:
      - gfortran
      - libboost-python-dev
      - python-vtk

before_install:
  - |
    git clone git://github.com/scikit-build/scikit-ci ../scikit-ci
    pip install -r ../scikit-ci/requirements.txt
    mv ../scikit-ci/ci ../ci

install:
  - python ../ci/driver.py before_install
  - python ../ci/driver.py install

before_script:
  - python ../ci/driver.py before_build

script:
  - python ../ci/driver.py build
  - python ../ci/driver.py test

after_success:
  - python ../ci/driver.py after_test
