# Config file for automatic testing at travis-ci.org

branches:
 only:
  - master

language: python

matrix:
  include:
    - os: linux
      python: "3.4"
      env:
        - EXTRA_TEST_ARGS="--exclude pen2 --exclude tbabel"

    - os: linux
      python: "3.3"
      env:
        - EXTRA_TEST_ARGS="--exclude pen2 --exclude tbabel"

    - os: linux
      python: "2.7"
      env:
        - EXTRA_TEST_ARGS="--exclude pen2 --exclude tbabel"

    - os: osx
      language: generic
      env:
        - EXTRA_TEST_ARGS="--exclude pen2 --exclude tbabel"


before_script:
  - "\
    if [ \"$START_XVFB\" = '1' ] ; then \
      export DISPLAY=':99.0' ; \
      cat /etc/init.d/xvfb ; \
      sh -e /etc/init.d/xvfb start ; \
      sleep 10 ; \

      export PYTHONPATH=\"/usr/lib/pymodules/python2.7:$PYTHONPATH\" ; \
    fi"

addons:
  apt:
    packages:
      - gfortran
      - libboost-python-dev
      - python-vtk

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - ./ci/travis_install.sh

# command to run tests, e.g. python setup.py test
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then flake8 -v; fi
  - ls /usr/local/bin
  - export PATH=/usr/local/bin:$PATH; python setup.py test --args="$EXTRA_TEST_ARGS"

after_success:
  - codecov -X gcov --required --file tests/coverage.xml
